### ISSUE TITLE
Hitting error calculate_all_coords in left_click_xy_natural() pretty often when using the click method outlined.  Any ideas?

### ISSUE THREAD

**Issue by jersmo** [hansalemaos/mousekey#1]
def mclick(x, y):
	mkey.left_click_xy_natural(
		x, y,
		delay=.2,  # duration of the mouse click (down - up)
		min_variation=-3,  # a random value will be added to each pixel  - define the minimum here
		max_variation=3,  # a random value will be added to each pixel  - define the maximum here
		use_every=4,  # use every nth pixel
		sleeptime=(0.005, 0.009),  # delay between each coordinate
		print_coords=True,  # console output
		percent=90,  # the lower, the straighter the mouse movement
		)

 :\Users\jerem\AppData\Local\Programs\Python\Python39\lib\site-packages\mousekey\__init__.py:1135: RuntimeWarning: invalid value encountered in scalar divide
  np.arange(
Traceback (most recent call last):
  File "C:\Users\jerem\Documents\newfish\safefish.py", line 223, in <module>
  sell_fish()
  File "C:\Users\jerem\Documents\newfish\safefish.py", line 149, in sell_fish
    mclick(random.randint(1180, 1230), random.randint(936, 997))
  File "C:\Users\jerem\Documents\newfish\safefish.py", line 30, in mclick
    mkey.left_click_xy_natural(
  File "C:\Users\jerem\AppData\Local\Programs\Python\Python39\lib\site-packages\mousekey\__init__.py", line 1299, in left_click_xy_natural
    natural_mouse_movement(
  File "C:\Users\jerem\AppData\Local\Programs\Python\Python39\lib\site-packages\mousekey\__init__.py", line 1180, in natural_mouse_movement
    alla = calculate_all_coords(allco)
  File "C:\Users\jerem\AppData\Local\Programs\Python\Python39\lib\site-packages\mousekey\__init__.py", line 1135, in calculate_all_coords

**Comment by jersmo** [comment]
Is min variation really meant to be a negative?

min_variation=-3

**Comment by hansalemaos** [comment]
Hi there! Thanks for your post. Yes, it can be negative, it just has to be a valid range. 
Is the click working? Could you please tell me what coords you see on the screen when you activate: print_coords=True Try to update your Python to 3.10, I didn't test it with 3.9.

**Comment by ViniciusGGT** [comment]
Hello. I believe I've found the source of the issue and have added a pull request solving it. In summary, the lines "// np.abs(d0)," and "// np.abs(d1)," would eventually give an error if d0, d1 or both were 0 (because then in those cases said lines would be dividing by 0). This meant all_coords didn't work if the mouse movement was with no movement (d0 == 0 and d1 == 0), vertical-only movement (d0 == 0), or horizontal-only movement (d1 == 0), so I added a different logic for those specific cases. This type of movement could happen, for example, if you were clicking multiple times in the same general area (like putting pmk.move_to_natural(randint(0, 10), randint(0, 10) in a loop), which was my case and I believe may have been yours too
